swagger: '2.0'
info:
  version: '0.1.0'
  title: Open Affect API
  description: API to record emotions
  termsOfService: none
  contact:
    name: Open Affect API team
    email: info@openaffect.io
    url: http://openaffect.io
  license:
    name: MIT
    url: http://opensource.org/licenses/MIT
host: 192.168.99.100
basePath: /api
schemes:
  - http
paths:
  /measures:
    post:
      description: report a new measure (used by a sensor)
      operationId: reportMeasure
      consumes:
        - application/json
      parameters:
        - name: measure
          in: body
          description: measure reported by the sensor
          required: true
          schema:
            $ref: '#/definitions/measure'
      responses:
        '201':
          description: no body
          schema:
            type: object
    get:
      description: list reported measures
      operationId: listMeasures
      consumes:
      produces:
        - application/json
      responses:
        '200':
          description: list of measures
          schema:
            type: array
            items: 
              $ref: '#/definitions/measure'
definitions:
  measure:
    type: object
    required:
      - timestamp
      - emotion
      - subject
      - trigger
      - sensor
    properties:
      timestamp:
        type: string
        format: date-time
      emotion:
        $ref: '#/definitions/emotion'
      subject:
        $ref: '#/definitions/tresource'
      trigger:
        $ref: '#/definitions/tresource'
      sensor:
        $ref: '#/definitions/tresource'
  tresource:
      type: object
      required:
        - href
        - type
        - properties
      properties:
        href:
          type: string
        type:
          type: string
        properties:
          type: object
          additionalProperties:
            type: object
  emotion:
    type: object
    required:
      - category
      - intensity
    properties:
      intensity:
        type: number
        format: double
      category:
        type: string