version: '3.1'
services:
  mysql:
    build: ../docker-images/mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --secure-file-priv=""
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/data/db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '6060:80'
    links:
      - mysql:db

volumes: 
  mysql_data: