-- MySQL Script generated by MySQL Workbench
-- Thu Jan  9 11:22:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema travel_api
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `travel_api` ;

-- -----------------------------------------------------
-- Schema travel_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `travel_api` DEFAULT CHARACTER SET utf8 ;
USE `travel_api` ;

-- -----------------------------------------------------
-- Table `travel_api`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_api`.`User` ;

CREATE TABLE IF NOT EXISTS `travel_api`.`User` (
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_api`.`City`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_api`.`City` ;

CREATE TABLE IF NOT EXISTS `travel_api`.`City` (
  `idCity` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idCity`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_api`.`Reason`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_api`.`Reason` ;

CREATE TABLE IF NOT EXISTS `travel_api`.`Reason` (
  `idReason` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReason`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `travel_api`.`Trip`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `travel_api`.`Trip` ;

CREATE TABLE IF NOT EXISTS `travel_api`.`Trip` (
  `idTrip` INT NOT NULL AUTO_INCREMENT,
  `visited` TINYINT NULL,
  `date` DATE NULL,
  `User_email` VARCHAR(45) NOT NULL,
  `City_idCity` INT NOT NULL,
  `Reason_idReason` INT NOT NULL,
  PRIMARY KEY (`idTrip`),
  INDEX `fk_Trip_User_idx` (`User_email` ASC) VISIBLE,
  INDEX `fk_Trip_City1_idx` (`City_idCity` ASC) VISIBLE,
  INDEX `fk_Trip_Reason1_idx` (`Reason_idReason` ASC) VISIBLE,
  CONSTRAINT `fk_Trip_User`
    FOREIGN KEY (`User_email`)
    REFERENCES `travel_api`.`User` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trip_City1`
    FOREIGN KEY (`City_idCity`)
    REFERENCES `travel_api`.`City` (`idCity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trip_Reason1`
    FOREIGN KEY (`Reason_idReason`)
    REFERENCES `travel_api`.`Reason` (`idReason`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
