-- MySQL Script generated by MySQL Workbench
-- Sun Nov 10 21:05:46 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema authentication_api
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `authentication_api` ;

-- -----------------------------------------------------
-- Schema authentication_api
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `authentication_api` DEFAULT CHARACTER SET utf8 ;
USE `authentication_api` ;

-- -----------------------------------------------------
-- Table `authentication_api`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authentication_api`.`User` ;

CREATE TABLE IF NOT EXISTS `authentication_api`.`User` (
  `email` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NULL,
  `lastname` VARCHAR(255) NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
